name: gym-duckietown
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.11
    - pytorch
    - torchvision
    - pyzmq
    - numpy
    - pyyaml
    - pip:
        - gymnasium
        - pyglet>=2.0.0
        - opencv-python
        - scikit-image
